#!/bin/sh
EMMC_DEV="/dev/mmcblk3"
PATH=/sbin:/bin:/usr/sbin:/usr/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/usr/lib
runlevel=S
umask 022
export PATH LD_LIBRARY_PATH runlevel
echo "Starting rcS..."
mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
/bin/hostname -F /etc/hostname
echo "mount emmc..."
mkdir /mnt/emmc

if [ -b "${EMMC_DEV}p6" ] || [ -b "${EMMC_DEV}6" ]; then
    echo "found userdata partition ..."
    if [ -b "${EMMC_DEV}p6" ]; then
        mount  -t ext4 ${EMMC_DEV}p6 /mnt/emmc -o nodelalloc,commit=5
    else
        mount  -t ext4 ${EMMC_DEV}6 /mnt/emmc -o nodelalloc,commit=5
    fi
else
    echo "warning: can't found userdata partition"
fi

kernel_version=$(uname -r)
if [ -z "$kernel_version" ]; then
    echo "Failed to retrieve kernel version information. Please check the system status."
    exit 1
fi
folder_path="/lib/modules/$kernel_version"
if [ -d "$folder_path" ]; then
    echo "The folder $folder_path already exists."
else
    mkdir -p "$folder_path"
    if [ $? -eq 0 ]; then
        echo "Folder $folder_path created successfully."
    else
        echo "Failed to create folder $folder_path. Please check the permissions."
        exit 1
    fi
fi
echo "rcS Complete"                                                                                                  
echo "Welcome to imx6q"
